// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import PptxGenJS from 'pptxgenjs';
import type { ImageItem, PptxInput, SlideData, TableData } from './types.js';
import type { Generator, GenerateContext } from './generator.js';
import { markdownToPptx } from './markdown.js';
import { computeSize, intrinsicSize, resolveImage, svgToPng } from './images.js';
import { renderPptxFromTemplate } from './pptTemplate.js';

type PptxApi = InstanceType<typeof PptxGenJS>;

// A style template is applied by rendering the deck natively on the template
// package (see pptTemplate.ts): slides carry placeholder shapes that inherit
// the template's layouts/theme/master so its styles actually apply.

export const pptxGenerator: Generator = {
  format: 'pptx',
  mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  extension: 'pptx',
  async generate(input: any, ctx?: GenerateContext): Promise<Buffer> {
    const p = markdownToPptx(String(input?.content || ''));
    p.title = (input.title as string) || p.title;
    p.author = (input.author as string) || p.author;
    input = p;
    // A style template is applied by rendering the deck natively on the
    // template package (placeholder shapes inherit the template's layouts).
    if (ctx?.styleTemplate) {
      try {
        return await renderPptxFromTemplate(input, ctx);
      } catch (err) {
        console.warn('[ai-doc] failed to render pptx with style template, falling back to default styling:', (err as Error).message);
      }
    }

    const pptx = new PptxGenJS();
    const themed = false;

    pptx.author = input.author ?? 'ai-doc';
    pptx.title = input.title;
    pptx.layout = 'LAYOUT_WIDE';

    const accent = '2F5496';
    const subtle = '666666';
    const body = '222222';

    const titleSlide = pptx.addSlide();
    titleSlide.addText(input.title, { x: 0.5, y: 1.6, w: 12, h: 1.5, fontSize: 36, bold: true, align: 'center', color: accent });
    if (input.author) {
      titleSlide.addText(`by ${input.author}`, { x: 0.5, y: 3.2, w: 12, h: 0.5, fontSize: 16, align: 'center', color: subtle });
    }
    titleSlide.addNotes(`Generated by ai-doc for: ${input.title}`);

    for (const slide of input.slides) {
      await addContentSlide(pptx, slide, { accent, subtle, body, themed });
    }

    return Buffer.from(await pptx.write('nodebuffer'));
  },
};

async function addContentSlide(pptx: PptxApi, slide: SlideData, c: { accent?: string; subtle?: string; body?: string; themed: boolean }): Promise<void> {
  const s = pptx.addSlide();
  const layout = slide.layout ?? 'title_content';
  const footerY = 6.9;

  if (layout === 'title') {
    if (slide.title) s.addText(slide.title, { x: 0.7, y: 1.8, w: 11.6, h: 1.2, fontSize: 32, bold: true, align: 'center', color: c.accent });
    if (slide.subtitle) s.addText(slide.subtitle, { x: 0.7, y: 3.2, w: 11.6, h: 0.8, fontSize: 18, align: 'center', color: c.subtle });
  } else {
    if (slide.title) s.addText(slide.title, { x: 0.5, y: 0.3, w: 12, h: 0.8, fontSize: 26, bold: true, color: c.accent });
    if (slide.subtitle) s.addText(slide.subtitle, { x: 0.5, y: 1.15, w: 12, h: 0.5, fontSize: 14, color: c.subtle });

    if (slide.tables && slide.tables.length > 0) {
      let y = 1.9;
      for (const t of slide.tables) {
        y = addSlideTable(s, t, y, c);
      }
      // images render below the table(s)
      if (slide.images?.length) {
        await addSlideImages(s, slide.images, y + 0.2, c, { fullHeight: 7.5, footerY });
      }
    } else {
      const bullets = slide.bullets ?? [];
      if (bullets.length > 0) {
        s.addText(bullets.map((b) => ({ text: b, options: { bullet: { code: '2022' } } })), {
          x: 0.6,
          y: 1.9,
          w: 11.8,
          h: 4.2,
          fontSize: 16,
          color: c.body,
          valign: 'top',
        });
      }
      if (slide.images?.length) {
        // if there is text content keep images in the lower band, otherwise
        // let them use the middle of the slide
        const startY = bullets.length > 0 ? 5.6 : 2.4;
        await addSlideImages(s, slide.images, startY, c, { fullHeight: 7.5, footerY });
      }
    }
  }

  if (slide.footer) s.addText(slide.footer, { x: 0.4, y: footerY, w: 11, h: 0.3, fontSize: 9, color: '999999', align: 'left' });
}

/** Render a table on the slide and return the y position after it. */
function addSlideTable(s: ReturnType<PptxApi['addSlide']>, t: TableData, startY: number, c: { accent?: string; body?: string; themed: boolean }): number {
  const cols = t.columns ?? Object.keys(t.rows[0] ?? {}).map((k) => ({ key: k, header: k }));
  const headers = c.themed ? c.accent : '2F5496';
  const headerRow = cols.map((col) => ({ text: col.header, options: { bold: true, fill: { color: headers }, color: 'FFFFFF' } }));
  const bodyRows = t.rows.map((row) => cols.map((col) => { const v = row[col.key]; return v === null || v === undefined ? '' : String(v); }));
  const tableW = 12.1;
  const rowH = 0.34;
  const colW = cols.map(() => Math.round((tableW / cols.length) * 100) / 100);
  s.addTable([headerRow, ...bodyRows], {
    x: 0.6,
    y: startY,
    w: tableW,
    colW,
    rowH,
    border: { type: 'solid', color: 'B4B4B4', pt: 0.5 },
    fill: { color: 'FFFFFF' },
    color: c.body ?? '222222',
    fontFace: 'Arial',
    fontSize: 12,
    align: 'center',
    valign: 'middle',
    margin: 0.05,
    autoPage: false,
  });
  return startY + (bodyRows.length + 1) * rowH;
}

/** Render images stacked below startY, honoring width/height/align/caption. */
async function addSlideImages(
  s: ReturnType<PptxApi['addSlide']>,
  images: ImageItem[],
  startY: number,
  c: { subtle?: string },
  bounds: { fullHeight: number; footerY: number },
): Promise<number> {
  let y = startY;
  const maxW = 12.1;
  const safeEnd = bounds.footerY - 0.2;
  // distribute the available band height evenly across all figures so the
  // first one does not starve the others
  const slot = images.length > 0 ? Math.max(0.5, (safeEnd - startY) / images.length) : 0;
  for (const img of images) {
    // pptxgenjs cannot embed vector SVG in a way PowerPoint can display, so
    // rasterize SVG to PNG (kept at native resolution) like PDF/XLSX do.
    const resolvedRaw = await resolveImage(img);
    let buffer = resolvedRaw.buffer;
    let mime = resolvedRaw.mimeType;
    if (resolvedRaw.kind === 'svg') {
      const { png } = await svgToPng(resolvedRaw.buffer);
      buffer = png;
      mime = 'image/png';
    }
    const intrinsic = intrinsicSize(buffer, 'png');

    const dataUri = `data:${mime};base64,` + buffer.toString('base64');

    // Explicit position (px, 96px = 1in) wins: place the image at an exact spot
    // with explicit size instead of auto-laying it out below the text.
    if (img.position) {
      const wIn = (img.position.w ?? computeSize({ width: resolvedRaw.width, height: resolvedRaw.height }, intrinsic, 320).width) / 96;
      const hIn = (img.position.h ?? computeSize({ width: resolvedRaw.width, height: resolvedRaw.height }, intrinsic, 320).height) / 96;
      const x = img.position.x / 96;
      const y = img.position.y / 96;
      s.addImage({ data: dataUri, x, y, w: Math.round(wIn * 100) / 100, h: Math.round(hIn * 100) / 100 });
      if (resolvedRaw.caption) {
        s.addText(resolvedRaw.caption, { x, y: y + hIn + 0.05, w: wIn, h: 0.3, fontSize: 10, italic: false, color: c.subtle ?? '999999', align: 'center' });
      }
      continue;
    }

    const sizePx = computeSize({ width: resolvedRaw.width, height: resolvedRaw.height }, intrinsic, 320);
    let wIn = sizePx.width / 96;
    let hIn = sizePx.height / 96;
    // scale the figure (plus any caption) down so it fits its slot
    const slotH = hIn + (resolvedRaw.caption ? 0.45 : 0.15);
    const scale = Math.min(1, maxW / (wIn || 1), slot > 0 ? slot / (slotH || 1) : 1);
    wIn *= scale;
    hIn *= scale;

    let x = 0.6;
    if (resolvedRaw.align === 'center') x = (13.33 - wIn) / 2;
    else if (resolvedRaw.align === 'right') x = 13.33 - 0.6 - wIn;

    s.addImage({ data: dataUri, x, y, w: Math.round(wIn * 100) / 100, h: Math.round(hIn * 100) / 100 });
    y += slot;
    if (resolvedRaw.caption) {
      s.addText(resolvedRaw.caption, { x, y: y - 0.4, w: wIn, h: 0.3, fontSize: 10, italic: false, color: c.subtle ?? '999999', align: 'center' });
    }
    if (y >= safeEnd) break;
  }
  return y;
}
