// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import PptxGenJS from 'pptxgenjs';
import type { PptxInput, SlideData } from './types.js';
import type { Generator } from './generator.js';

type PptxApi = InstanceType<typeof PptxGenJS>;

export const pptxGenerator: Generator = {
  format: 'pptx',
  mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  extension: 'pptx',
  async generate(input: PptxInput): Promise<Buffer> {
    const pptx = new PptxGenJS();
    pptx.author = input.author ?? 'ai-doc';
    pptx.title = input.title;
    pptx.layout = 'LAYOUT_WIDE';

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.addText(input.title, { x: 0.5, y: 1.6, w: 12, h: 1.5, fontSize: 36, bold: true, align: 'center', color: '2F5496' });
    if (input.author) {
      titleSlide.addText(`by ${input.author}`, { x: 0.5, y: 3.2, w: 12, h: 0.5, fontSize: 16, align: 'center', color: '666666' });
    }
    titleSlide.addNotes(`Generated by ai-doc for: ${input.title}`);

    for (const slide of input.slides) {
      addContentSlide(pptx, slide);
    }

    const buf = await pptx.write('nodebuffer');
    return Buffer.from(buf);
  },
};

function addContentSlide(pptx: PptxApi, slide: SlideData): void {
  const s = pptx.addSlide();
  const layout = slide.layout ?? 'title_content';

  if (layout === 'title') {
    if (slide.title) s.addText(slide.title, { x: 0.7, y: 2.0, w: 11.6, h: 1.2, fontSize: 32, bold: true, align: 'center', color: '2F5496' });
    if (slide.subtitle) s.addText(slide.subtitle, { x: 0.7, y: 3.4, w: 11.6, h: 0.8, fontSize: 18, align: 'center', color: '444444' });
  } else {
    if (slide.title) s.addText(slide.title, { x: 0.5, y: 0.3, w: 12, h: 0.8, fontSize: 26, bold: true, color: '2F5496' });
    if (slide.subtitle) s.addText(slide.subtitle, { x: 0.5, y: 1.15, w: 12, h: 0.5, fontSize: 14, color: '666666' });
    const bullets = slide.bullets ?? [];
    if (bullets.length > 0) {
      s.addText(bullets.map((b) => ({ text: b, options: { bullet: { code: '2022' } } })), {
        x: 0.6,
        y: 1.9,
        w: 11.8,
        h: 4.2,
        fontSize: 16,
        color: '222222',
        valign: 'top',
      });
    }
  }

  if (slide.footer) s.addText(slide.footer, { x: 0.4, y: 6.9, w: 11, h: 0.3, fontSize: 9, color: '999999', align: 'left' });
}
