import { reactive } from 'vue';

export const state = reactive({
  user: null,
  lang: localStorage.getItem('lang') || (navigator.language && navigator.language.startsWith('zh') ? 'zh-CN' : 'en-US'),
  theme: localStorage.getItem('theme') || 'light',
  meta: null,
  filesPage: { page: 1, limit: 20, total: 0, pages: 1, owners: [] },
});

const I18N = {
  'zh-CN': {
    'nav.files': '生成文件',
    'nav.generate': '在线生成',
    'nav.styles': '样式模板',
    'nav.users': '用户管理',
    'nav.sso': 'SSO 登录',
    'nav.audit': '审计日志',
    'brand.sub': '文档生成管理后台',
    'common.refresh': '刷新',
    'common.searchPlaceholder': '搜索文件名/格式/属主…',
    'common.empty': '暂无数据',
    'common.pagination': '共 {total} 条',
    'common.page': '第 {page} / {pages} 页',
    'common.action.preview': '预览',
    'common.action.download': '下载',
    'common.action.transfer': '分配',
    'common.action.delete': '删除',
    'common.loadFailed': '加载失败: {msg}',
    'files.title': '生成的文档',
    'files.subtitle': '预览或下载已生成的文档',
    'files.col.name': '文件名',
    'files.col.format': '格式',
    'files.col.size': '大小',
    'files.col.time': '创建时间',
    'files.col.owner': '归属',
    'files.col.actions': '操作',
    'files.ownerFilter': '按属主筛选',
    'files.allOwner': '全部属主',
    'gen.title': '在线生成',
    'gen.subtitle': '输入 Markdown 内容，一键生成 Word / PDF / Excel / PPT 文档',
    'gen.format': '文档格式',
    'gen.titlePlaceholder': '（可选）文档标题',
    'gen.filenamePlaceholder': '如 Q3经营报告、2025年度总结',
    'gen.filenameTextPlaceholder': '如 main.cpp、index.html、note.txt（需含扩展名）',
    'gen.filename': '文件名',
    'gen.style': '套用样式模板',
    'gen.styleNone': '（不使用）',
    'gen.example': '载入示例',
    'gen.clear': '清空',
    'gen.contentLabel': 'Markdown 内容',
    'gen.textContentLabel': '纯文本内容（原样保存）',
    'gen.encoding': '文本编码',
    'gen.lineEnding': '行尾序列',
    'gen.textOption': '文本 (txt / html / 源码)',
    'gen.contentRequired': '请输入 Markdown 内容',
    'gen.filenameRequired': '请输入文件名',
    'gen.generate': '生成文档',
    'gen.generating': '生成中…',
    'gen.genOk': '生成成功',
    'gen.genFailed': '生成失败',
    'gen.genLink': '链接',
    'gen.genDownload': '下载',
    'gen.preview': '预览',
    'account.logout': '退出登录',
    'account.changePassword': '修改密码',
    'login.title': 'AI-Doc',
    'login.subtitle': '文档生成管理后台',
    'login.username': '用户名',
    'login.password': '密码',
    'login.submit': '登录',
    'login.sso': '统一登录',
    'login.orSso': '或使用单点登录',
    'login.error': '登录失败: {msg}',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'styles.subtitle': '上传真实文档作为版式模板，生成同格式文档时自动套用其主题与样式',
    'styles.namePlaceholder': '模板名称（可选）',
    'styles.chooseFile': '选择文件',
    'styles.asSystem': '作为系统模板（管理员）',
    'styles.upload': '上传样式模板',
    'styles.unsupported': '仅支持 .pptx / .docx / .xlsx',
    'styles.col.name': '名称',
    'styles.col.format': '格式',
    'styles.col.current': '当前使用',
    'styles.col.filename': '文件名',
    'styles.col.size': '大小',
    'styles.current': '当前使用',
    'styles.setSystemDefault': '设为系统默认',
    'styles.setMyDefault': '设为我的默认',
    'styles.deleteConfirm': '确定删除该样式模板吗？',
    'users.subtitle': '管理系统账号与角色，并可重置密码',
    'users.add': '新增用户',
    'users.col.username': '用户名',
    'users.col.displayName': '显示名',
    'users.col.role': '角色',
    'users.col.origin': '来源',
    'users.col.createdAt': '创建时间',
    'users.role.admin': '管理员',
    'users.role.user': '普通用户',
    'users.rename': '改名',
    'users.promote': '设为管理员',
    'users.resetPwd': '重置密码',
    'users.deleteConfirm': '确定删除用户 {name}？',
    'sso.subtitle': '界面化配置 OIDC / SAML / CAS 身份提供商',
    'sso.test': '测试连接',
    'sso.save': '保存配置',
    'sso.enabled': '启用 SSO',
    'sso.provider': '协议类型',
    'sso.autoCreate': '首次 SSO 登录自动创建账号',
    'sso.baseUrl': '回调基地址',
    'sso.adminUsernames': 'SSO 管理员用户名（逗号分隔）',
    'sso.loadMetadata': '获取元数据',
    'audit.subtitle': '记录登录、文件、模板、用户与 SSO 等操作，便于追踪',
    'audit.search': '搜索详情/目标',
    'audit.actor': '按操作人',
    'audit.allActions': '全部操作类型',
    'audit.clear': '清空日志',
    'audit.clearConfirm': '确定清空全部审计日志吗？不可恢复。',
    'audit.col.time': '时间',
    'audit.col.actor': '操作人',
    'audit.col.action': '操作类型',
    'audit.col.target': '目标',
    'audit.col.detail': '详情',
    'audit.action.file.generate': '生成文档',
    'audit.action.file.download': '下载文档',
    'audit.action.file.delete': '删除文档',
    'audit.action.file.transfer': '分配归属',
    'audit.action.login': '登录',
    'audit.action.logout': '退出登录',
    'audit.action.auth.password': '修改密码',
    'audit.action.sso.update': 'SSO 配置',
    'audit.action.user.create': '创建用户',
    'audit.action.user.role': '设置角色',
    'audit.action.user.rename': '重命名用户',
    'audit.action.user.password': '重置密码',
    'audit.action.user.delete': '删除用户',
    'audit.action.styletemplate.upload': '上传样式模板',
    'audit.action.styletemplate.delete': '删除样式模板',
    'audit.action.styletemplate.download': '下载样式模板',
    'audit.action.styletemplate.promote': '设为系统模板',
    'audit.action.styletemplate.default': '设为默认模板',
    'audit.action.audit.clear': '清空审计日志',
    'dev.inprogress': '该功能正在开发中，敬请期待',
  },
  'en-US': {
    'nav.files': 'Files',
    'nav.generate': 'Generate',
    'nav.styles': 'Style Templates',
    'nav.users': 'Users',
    'nav.sso': 'SSO Login',
    'nav.audit': 'Audit Log',
    'brand.sub': 'Document Generation Console',
    'common.refresh': 'Refresh',
    'common.searchPlaceholder': 'Search name / format / owner…',
    'common.empty': 'No data yet',
    'common.pagination': '{total} items',
    'common.page': 'Page {page} / {pages}',
    'common.action.preview': 'Preview',
    'common.action.download': 'Download',
    'common.action.transfer': 'Assign',
    'common.action.delete': 'Delete',
    'common.loadFailed': 'Load failed: {msg}',
    'files.title': 'Generated Documents',
    'files.subtitle': 'Preview or download generated documents',
    'files.col.name': 'File Name',
    'files.col.format': 'Format',
    'files.col.size': 'Size',
    'files.col.time': 'Created',
    'files.col.owner': 'Owner',
    'files.col.actions': 'Actions',
    'files.ownerFilter': 'Filter by owner',
    'files.allOwner': 'All owners',
    'gen.title': 'Generate Online',
    'gen.subtitle': 'Write Markdown and generate Word / PDF / Excel / PPT',
    'gen.format': 'Format',
    'gen.titlePlaceholder': '(optional) Document title',
    'gen.filenamePlaceholder': 'e.g. Q3 report',
    'gen.filenameTextPlaceholder': 'e.g. main.cpp, index.html, note.txt (include extension)',
    'gen.filename': 'File name',
    'gen.style': 'Style template',
    'gen.styleNone': '(none)',
    'gen.example': 'Load example',
    'gen.clear': 'Clear',
    'gen.contentLabel': 'Markdown content',
    'gen.textContentLabel': 'Plain text content (saved as-is)',
    'gen.encoding': 'Encoding',
    'gen.lineEnding': 'Line ending',
    'gen.textOption': 'Text (txt / html / source)',
    'gen.contentRequired': 'Please enter Markdown content',
    'gen.filenameRequired': 'Please enter a file name',
    'gen.generate': 'Generate',
    'gen.generating': 'Generating…',
    'gen.genOk': 'Generated',
    'gen.genFailed': 'Generation failed',
    'gen.genLink': 'Link',
    'gen.genDownload': 'Download',
    'gen.preview': 'Preview',
    'account.logout': 'Sign out',
    'account.changePassword': 'Change password',
    'login.title': 'AI-Doc',
    'login.subtitle': 'Document Generation Console',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Sign in',
    'login.sso': 'Single Sign-On',
    'login.orSso': 'or use single sign-on',
    'login.error': 'Sign-in failed: {msg}',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'styles.subtitle': 'Upload real document files as layout templates — apply their theme to same-format documents',
    'styles.namePlaceholder': 'Name (optional)',
    'styles.chooseFile': 'Choose file',
    'styles.asSystem': 'As system template (admin)',
    'styles.upload': 'Upload Style Template',
    'styles.unsupported': 'Only .pptx / .docx / .xlsx supported',
    'styles.col.name': 'Name',
    'styles.col.format': 'Format',
    'styles.col.current': 'In Use',
    'styles.col.filename': 'File Name',
    'styles.col.size': 'Size',
    'styles.current': 'In use',
    'styles.setSystemDefault': 'Set as system default',
    'styles.setMyDefault': 'Set as my default',
    'styles.deleteConfirm': 'Delete this style template?',
    'users.subtitle': 'Manage accounts and roles, reset passwords',
    'users.add': 'New User',
    'users.col.username': 'Username',
    'users.col.displayName': 'Display Name',
    'users.col.role': 'Role',
    'users.col.origin': 'Origin',
    'users.col.createdAt': 'Created',
    'users.role.admin': 'Admin',
    'users.role.user': 'User',
    'users.rename': 'Rename',
    'users.promote': 'Make admin',
    'users.resetPwd': 'Reset password',
    'users.deleteConfirm': 'Delete user {name}?',
    'sso.subtitle': 'Configure OIDC / SAML / CAS identity providers',
    'sso.test': 'Test connection',
    'sso.save': 'Save config',
    'sso.enabled': 'Enable SSO',
    'sso.provider': 'Protocol',
    'sso.autoCreate': 'Auto-create account on first SSO login',
    'sso.baseUrl': 'Callback base URL',
    'sso.adminUsernames': 'SSO admin usernames (comma-separated)',
    'sso.loadMetadata': 'Fetch metadata',
    'audit.subtitle': 'Track logins, files, templates, users and SSO operations',
    'audit.search': 'Search detail / target',
    'audit.actor': 'By actor',
    'audit.allActions': 'All actions',
    'audit.clear': 'Clear log',
    'audit.clearConfirm': 'Clear ALL audit logs? This cannot be undone.',
    'audit.col.time': 'Time',
    'audit.col.actor': 'Actor',
    'audit.col.action': 'Action',
    'audit.col.target': 'Target',
    'audit.col.detail': 'Detail',
    'audit.action.file.generate': 'Generate document',
    'audit.action.file.download': 'Download document',
    'audit.action.file.delete': 'Delete document',
    'audit.action.file.transfer': 'Transfer owner',
    'audit.action.login': 'Sign in',
    'audit.action.logout': 'Sign out',
    'audit.action.auth.password': 'Change password',
    'audit.action.sso.update': 'SSO config',
    'audit.action.user.create': 'Create user',
    'audit.action.user.role': 'Set role',
    'audit.action.user.rename': 'Rename user',
    'audit.action.user.password': 'Reset password',
    'audit.action.user.delete': 'Delete user',
    'audit.action.styletemplate.upload': 'Upload style template',
    'audit.action.styletemplate.delete': 'Delete style template',
    'audit.action.styletemplate.download': 'Download style template',
    'audit.action.styletemplate.promote': 'Promote to system template',
    'audit.action.styletemplate.default': 'Set as default template',
    'audit.action.audit.clear': 'Clear audit log',
    'dev.inprogress': 'Coming soon',
  },
};

export function t(key, params) {
  let s = (I18N[state.lang] && I18N[state.lang][key]) || key;
  if (params) for (const k of Object.keys(params)) s = s.replace(`{${k}}`, params[k]);
  return s;
}

export function setLang(lang) {
  state.lang = lang;
  localStorage.setItem('lang', lang);
}

export function setTheme(theme) {
  state.theme = theme;
  localStorage.setItem('theme', theme);
  applyTheme();
}

export function applyTheme() {
  document.documentElement.classList.toggle('dark', state.theme === 'dark');
}
